name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install sdl
      run: sudo apt-get install libsdl2-2.0
    - name: install sdl font
      run: sudo apt-get install libsdl2-ttf-2.0-0
    - name: make
      run: make
